
import React, { useState, useEffect } from 'react';
import { Employee, Payroll, Xarun } from '../types';
import { API } from '../services/api';

interface HRMPayrollProps {
  employees: Employee[];
  xarumo: Xarun[];
}

const HRMPayroll: React.FC<HRMPayrollProps> = ({ employees, xarumo }) => {
  const [payrolls, setPayrolls] = useState<Payroll[]>([]);
  const [selectedMonth, setSelectedMonth] = useState(new Date().toLocaleString('en-US', { month: 'long' }));
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    loadPayrollData();
  }, [selectedMonth, selectedYear]);

  const loadPayrollData = async () => {
    const data = await API.payroll.getAll();
    setPayrolls(data.filter(p => p.month === selectedMonth && p.year === selectedYear));
  };

  const processPayroll = async () => {
    setIsProcessing(true);
    for (const emp of employees) {
      const existing = payrolls.find(p => p.employeeId === emp.id);
      if (!existing) {
        const newPay: Partial<Payroll> = {
          employeeId: emp.id,
          month: selectedMonth,
          year: selectedYear,
          baseSalary: emp.salary,
          bonus: 0,
          deduction: 0,
          netPay: emp.salary,
          status: 'UNPAID',
          xarunId: emp.xarunId
        };
        await API.payroll.save(newPay);
      }
    }
    await loadPayrollData();
    setIsProcessing(false);
  };

  const markAsPaid = async (payroll: Payroll) => {
    await API.payroll.save({ ...payroll, status: 'PAID', paymentDate: new Date().toISOString() });
    loadPayrollData();
  };

  const printPayslip = (payroll: Payroll) => {
    const emp = employees.find(e => e.id === payroll.employeeId);
    const xarun = xarumo.find(x => x.id === emp?.xarunId)?.name || 'N/A';
    
    const printWindow = window.open('', '_blank');
    if (printWindow && emp) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Payslip - ${emp.name}</title>
            <style>
              body { font-family: 'Inter', sans-serif; padding: 40px; }
              .slip { border: 2px solid #000; padding: 30px; border-radius: 10px; max-width: 600px; margin: auto; }
              .header { text-align: center; border-bottom: 2px dashed #ccc; padding-bottom: 20px; margin-bottom: 20px; }
              .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
              .total { font-weight: 900; font-size: 20px; margin-top: 20px; background: #f8fafc; padding: 15px; }
              .footer { text-align: center; font-size: 10px; color: #888; margin-top: 30px; }
            </style>
          </head>
          <body>
            <div class="slip">
              <div class="header">
                <h1>SmartStock Pro - PAYSLIP</h1>
                <p>${payroll.month} ${payroll.year} - ${xarun}</p>
              </div>
              <div class="row"><span>Employee Name:</span> <strong>${emp.name}</strong></div>
              <div class="row"><span>Employee ID:</span> <strong>${emp.employeeIdCode}</strong></div>
              <div class="row"><span>Position:</span> <strong>${emp.position}</strong></div>
              <div class="row"><span>Base Salary:</span> <strong>$${payroll.baseSalary}</strong></div>
              <div class="row"><span>Bonuses:</span> <strong>$${payroll.bonus}</strong></div>
              <div class="row"><span>Deductions:</span> <strong style="color:red">-$${payroll.deduction}</strong></div>
              <div class="total"><div class="row"><span>NET PAY:</span> <span>$${payroll.netPay}</span></div></div>
              <div class="footer">OFFICIAL SALARY RECEIPT - GENERATED BY SMARTSTOCK Pro HRM</div>
            </div>
            <script>window.onload = () => { window.print(); window.close(); }</script>
          </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  return (
    <div className="space-y-6">
      <div className="bg-white p-8 rounded-[3rem] shadow-sm border border-slate-100 flex flex-col md:flex-row justify-between items-center gap-6">
        <div>
          <h2 className="text-3xl font-black text-slate-800 tracking-tighter uppercase">Maamulka Mushaharka (Payroll)</h2>
          <p className="text-xs text-slate-400 font-bold uppercase tracking-widest mt-1">Xisaabi, Bedel, ama bixi mushaharka shaqaalaha bishii.</p>
        </div>
        
        <div className="flex gap-4">
          <select className="px-6 py-3 bg-slate-50 border-2 border-slate-100 rounded-2xl font-bold outline-none" value={selectedMonth} onChange={e => setSelectedMonth(e.target.value)}>
            {['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].map(m => <option key={m} value={m}>{m}</option>)}
          </select>
          <button onClick={processPayroll} disabled={isProcessing} className="bg-indigo-600 text-white px-8 py-3.5 rounded-2xl font-black shadow-lg hover:scale-105 active:scale-95 transition-all uppercase text-[10px] tracking-widest">
            {isProcessing ? 'PROCESSING...' : 'PROCESS MONTHLY PAYROLL'}
          </button>
        </div>
      </div>

      <div className="bg-white rounded-[3rem] shadow-sm border border-slate-100 overflow-hidden">
        <table className="w-full text-left">
          <thead>
            <tr className="bg-slate-50 text-slate-400 text-[10px] font-black uppercase tracking-widest border-b border-slate-100">
              <th className="px-10 py-6">Shaqaalaha</th>
              <th className="px-10 py-6">Mushaharka (Base)</th>
              <th className="px-10 py-6">Bonus/Deduction</th>
              <th className="px-10 py-6">Net Pay</th>
              <th className="px-10 py-6">Xaaladda</th>
              <th className="px-10 py-6 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {payrolls.map(pay => {
              const emp = employees.find(e => e.id === pay.employeeId);
              return (
                <tr key={pay.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-10 py-4">
                    <div className="flex items-center gap-4">
                      <img src={emp?.avatar} className="w-10 h-10 rounded-xl" alt="" />
                      <div>
                        <p className="font-black text-slate-700">{emp?.name}</p>
                        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">{emp?.position}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-10 py-4 font-bold text-slate-600">${pay.baseSalary}</td>
                  <td className="px-10 py-4">
                    <div className="flex flex-col text-[10px] font-black">
                      <span className="text-emerald-500">+{pay.bonus}</span>
                      <span className="text-rose-500">-{pay.deduction}</span>
                    </div>
                  </td>
                  <td className="px-10 py-4 text-lg font-black text-indigo-600">${pay.netPay}</td>
                  <td className="px-10 py-4">
                    <span className={`px-4 py-1.5 rounded-full text-[9px] font-black uppercase tracking-widest ${
                      pay.status === 'PAID' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'
                    }`}>
                      {pay.status}
                    </span>
                  </td>
                  <td className="px-10 py-4 text-right">
                    <div className="flex justify-end gap-2">
                      <button onClick={() => printPayslip(pay)} className="p-3 bg-slate-50 text-slate-500 rounded-xl shadow-sm hover:bg-slate-900 hover:text-white transition-all">🖨️</button>
                      {pay.status === 'UNPAID' && (
                        <button onClick={() => markAsPaid(pay)} className="bg-emerald-600 text-white px-6 py-2 rounded-xl text-[10px] font-black uppercase shadow-lg">MARK PAID</button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {payrolls.length === 0 && (
          <div className="py-20 text-center text-slate-300 font-black uppercase tracking-widest">Lama hayo xogta mushaharka ee bishan.</div>
        )}
      </div>
    </div>
  );
};

export default HRMPayroll;
